name: deploy #the workflowe name on the actions tab 

on:
  pull_request:
    branches: ["main"] #show the terraform plan on main
  push:
    branches: ["main"] #auto apply direct puishes to main

permissions: 
  id-token: write #this is requires as it lets this workflow req on oidc token
  contents: read #this is required to read the contents of the repository

env: 
  AWS_REGION: us-east-1 

jobs: 
  terraform: 
    runs-on: ubuntu-latest

    defaults: 
      run: 
        working-directory: infra #since .tf files are under infra, set it as the working directory

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4 #this will pull the repo inside the runner

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4 
        with: 
          role-to-assume: arn:aws:iam::163666916898:role/github-actions-terraform
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3 #installs terraform on the runner

      - name: Terraform Init
        run: terraform init #initializes providers and backend

      - name: Terraform fmt
        run: terraform fmt -check -recursive #ensure check and recursive, fails if code is not formatted

      - name: Terraform validate
        run: terraform validate #validates the code, catches errors

      - name: Terraform Plan
        if: github.event_name == 'pull_request' #only run terraform plan on pull requests
        run: terraform plan 

      - name: Terraform apply
        if: github.event_name == 'push' #only run terraform apply on pushes to main
        run: terraform apply -auto-approve #auto approve the plan and deploy on main